# Generated by Django 5.2.1 on 2025-08-23 04:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_type', models.CharField(choices=[('keep', 'Keep'), ('give', 'Give')], max_length=10)),
                ('last_checkup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkup_interval_months', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.CharField(max_length=255)),
                ('item_received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Keep', 'Keep'), ('Give', 'Give'), ('Donate', 'Donate')], default='Keep', max_length=10)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('Clothing_Accessories', 'Clothing & Accessories'), ('Personal_Care_Items', 'Personal Care Items'), ('Furniture_Appliances', 'Furniture & Appliances'), ('Decor_Art', 'Decor & Art'), ('Subscriptions_Licenses', 'Subscriptions & Licenses'), ('Technology', 'Technology'), ('Vehicles', 'Vehicles'), ('Tools_Equipment', 'Tools & Equipment'), ('Outdoor_Gear', 'Outdoor Gear'), ('Fitness_Equipment', 'Fitness Equipment'), ('Toys_Games', 'Toys & Games'), ('Pet_Supplies', 'Pet Supplies'), ('Books_Media', 'Books & Media'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], default='Other', max_length=30)),
                ('ownership_duration_goal_months', models.IntegerField(default=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
