# Generated by Django 5.2.1 on 2025-07-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkup',
            unique_together=set(),
        ),
    ]
