# Generated by Django 5.2.1 on 2025-08-23 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkup',
            unique_together={('user', 'checkup_type')},
        ),
    ]
