# Generated by Django 5.2.1 on 2025-06-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='picture_type',
            field=models.CharField(default='emoji', max_length=10),
        ),
    ]
