# Generated by Django 5.2.1 on 2025-08-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_add_checkup_unique_constraint"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE items_checkup DROP CONSTRAINT IF EXISTS items_checkup_checkup_type_eef0c1a3_uniq;",
            reverse_sql="ALTER TABLE items_checkup ADD CONSTRAINT items_checkup_checkup_type_eef0c1a3_uniq UNIQUE (checkup_type);",
        ),
    ]
