# Generated by Django 5.2.1 on 2025-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_checkup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item_type',
            field=models.CharField(choices=[('Household Item', 'Household Item'), ('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
