# Generated by Django 5.2.1 on 2026-02-19 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_checkup_type_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when location was last changed', null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='URL-safe version of display_name', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('full_path', models.CharField(db_index=True, help_text="Materialized path from root (e.g., 'home/bedroom/closet')", max_length=500)),
                ('level', models.IntegerField(default=0, help_text='Depth in hierarchy (0=root)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location in hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_path'],
            },
        ),
        migrations.AddField(
            model_name='owneditem',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current location of this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', 'full_path'], name='items_locat_user_id_bce6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['full_path'], name='items_locat_full_pa_091d07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'slug')},
        ),
    ]
