# Generated by Django 5.2.1 on 2025-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_owneditem_picture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='picture_url',
            field=models.TextField(),
        ),
    ]
