# Generated by Django 5.2.1 on 2025-06-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_owneditem_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owneditem',
            name='picture_type',
        ),
        migrations.AlterField(
            model_name='owneditem',
            name='picture_url',
            field=models.CharField(max_length=255),
        ),
    ]
