# Generated by Django 5.2.1 on 2025-08-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_ownership_duration_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item_type',
            field=models.CharField(choices=[('Household Item', 'Household Item'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Vehicle', 'Vehicle'), ('Books', 'Books'), ('Tools', 'Tools'), ('Office Supplies', 'Office Supplies'), ('Sports Equipment', 'Sports Equipment'), ('Toys', 'Toys'), ('Art', 'Art'), ('Music Instruments', 'Music Instruments'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
