# Generated by Django 5.2.1 on 2026-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_location_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item_type',
            field=models.CharField(choices=[('Cleaning_Supplies', 'Cleaning Supplies'), ('Clothing_Accessories', 'Clothing & Accessories'), ('Personal_Care_Items', 'Personal Care Items'), ('Furniture_Appliances', 'Furniture & Appliances'), ('Decor_Art', 'Decor & Art'), ('Subscriptions_Licenses', 'Subscriptions & Licenses'), ('Technology', 'Technology'), ('Vehicles', 'Vehicles'), ('Tools_Equipment', 'Tools & Equipment'), ('Outdoor_Gear', 'Outdoor Gear'), ('Fitness_Equipment', 'Fitness Equipment'), ('Toys_Games', 'Toys & Games'), ('Pet_Supplies', 'Pet Supplies'), ('Books_Media', 'Books & Media'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
