# Generated by Django 5.2.1 on 2025-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_owneditem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item_type',
            field=models.CharField(choices=[('Clothing_Accessories', 'Clothing & Accessories'), ('Technology', 'Technology'), ('Furniture_Appliances', 'Furniture & Appliances'), ('Kitchenware', 'Kitchenware'), ('Books_Media', 'Books & Media'), ('Vehicles', 'Vehicles'), ('Personal_Care_Items', 'Personal Care Items'), ('Decor_Art', 'Decor & Art'), ('Tools_Equipment', 'Tools & Equipment'), ('Toys_Games', 'Toys & Games'), ('Outdoor_Gear', 'Outdoor Gear'), ('Fitness_Equipment', 'Fitness Equipment'), ('Pet_Supplies', 'Pet Supplies'), ('Subscriptions_Licenses', 'Subscriptions & Licenses'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
