# Generated by Django 5.2 on 2025-04-29 05:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.CharField(max_length=255)),
                ('item_received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Keep', 'Keep'), ('Give', 'Give'), ('Donate', 'Donate')], default='Keep', max_length=10)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Household Item', 'Household Item'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_type', models.CharField(choices=[('keep', 'Keep'), ('give', 'Give')], max_length=10)),
                ('last_checkup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkup_interval_months', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('checkup_type',)},
            },
        ),
    ]
