# Generated by Django 5.2 on 2025-05-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkup',
            unique_together=set(),
        ),
    ]
