# Generated by Django 5.2.1 on 2025-05-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkups",
                to="users.user",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkup",
            unique_together={("user", "checkup_type")},
        ),
        migrations.AlterField(
            model_name="checkup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkups",
                to="users.user",
                null=False,
            ),
        ),
    ]
