# Generated by Django 5.2 on 2025-05-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_checkup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkup',
            unique_together={('checkup_type',)},
        ),
    ]
